@KedaiOnline.API_HostAddress = https://localhost:7039
@token =  CfDJ8FcEiKa3i-ZKiQfyrPLUBAOWYOx3Ac_IZw5m5kwCp5__vD6LVc7M1afB4B_3f8tbrBgwMxzfgV2otQfni0tDoVrtuubgZD7mBR3ssMa_Q1ZSa7WPpiSnWjKp26FkIqvvlp7KRsOk77-oB1G2ZRomSXX4uwg8vbB4PmBUZOdDjaZPO_OIBa2HMjXCeIORCZgkrD5FMoedV1a75IGfb_QHPei-XLg60MVZzHKrm6scvO6xAoEyXHmhUpghv-JJh_fsldSMZ8WEstmiOqna5AycszncMNyx8J9NUu1hErz9lXAuyo9loZuehulAbHzNpQZFCLxLzatYwvd0rE93HwSwuk6vwEp3ZaX1rI9c5kfOpxxtdnCOBie0xLNkIMPh8ugYvjqZvgl-5dS9ltkTd4A8u7db6d4-uGeW4TMM_CrfJynf47InUaU_7t5QuuPNZauxhjdCdJXCkG1E0g_9VrGRI9u9NFz4hwUdleLG3YMoM87iCWZXLZ-EET0G_IL0wIaNwSTv1onsxhfc12__6ujWZWZxnyMQCPVLNwzTyQelWAX0kivHRS42b6hDjlXjgyJHRgC6QZ5D4CaLCT2epnGImYgWk-37eNgRtJoQPOjiXIeeCCjqOTbAoqCYgpRM_puFhBZC_uHic0iNafNCARRnXrQRaxv4dF-X4eLpd7v2D2R2FThBp5x4huUAOGbrkiaOSYXz9lSaHDvcz96JEd-cgfl96younYh89z3MUnn47Bn9d3ufCmJD8BLBvBMfWauAdAuPWPil9NB84MUDVctWgFDL7YyJ479zGVq8bvlV6zYQC06Rto0bK6RUSnsu_WcnSSeVts_SUArqHs53JXzzCnOlvKVO2OvDZijUBmOv1iH33jpaQDp2h56N4kQ-AfZ56w

GET {{KedaiOnline.API_HostAddress}}/api/kedaionline
Authorization: Bearer {{token}}
###

GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/1
Authorization: Bearer {{token}}

###

DELETE {{KedaiOnline.API_HostAddress}}/api/kedaionline/8

###

POST {{KedaiOnline.API_HostAddress}}/api/kedaionline
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Nama" : "Kedai 13",
    "Description" : "Kedai 13 Description",
    "Category" : "Nasi Kerabu",
    "HasDelivery" : "tidak",
    "ContactEmail" : "kedai12@test.com",
    "ContactNumber" : "0123456789",
    "City" : "Ayer Keroh",
    "Street" : "Jalan Ayer Keroh",
    "PostalCode" : "75-450"
}

###
GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/3

###
GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/10

###
PATCH {{KedaiOnline.API_HostAddress}}/api/kedaionline/8
Content-Type: application/json

{
    "Nama" : "Kedai 13",
    "Description" : "Kedai 12 Description",
    "HasDelivery" : "ya"
}

###

POST {{KedaiOnline.API_HostAddress}}/api/kedaionline/1/items
Content-Type: application/json

{
    "Name" : "Item 161",
    "Description" : "Item 161 Description",
    "Price" : 10.00
}

###

GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/1/items/
Authorization : Bearer {{token}}

###

DELETE {{KedaiOnline.API_HostAddress}}/api/kedaionline/1/items/

###

GET https://localhost:7039/api/kedaionline/1/items/27

###

POST {{KedaiOnline.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email" : "owner@test.com",
    "password" : "Password1!"
}

###

POST {{KedaiOnline.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email" : "owner@test.com",
    "password" : "Password1!"
}

###
PATCH {{KedaiOnline.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nationality" : "Malaysia",
  "DateOfBirth" : "2010-01-01"
}

###
