@KedaiOnline.API_HostAddress = https://localhost:7039
@token = CfDJ8FcEiKa3i-ZKiQfyrPLUBAPkB47e2IyfoP1WulHybYiaVuD9vsyFKbV8c563HE5DP2fExcMyakasn0rW9lW5FJXdYvPp8msKvOpdAaw_reaC44lmwpbiNu_IIsmpSW-xKEuXOO1lLllOtSaNT4G4SPE2hskj2XLc8B72p0wnkr23TMOcmb90keXSoMuJ9nk42cbtzZ8x0rvBuFaSstpZ9ut-LTQ964nQPkkXn0U1IgKvjbAksN57bt7zDntrnbqRz237RsCwwHNhcSdNos6gq0qNK-4z5Dy4KIisJTEI7N-325a4aIrj9cfuY1B_XkxbKzm73QBf6ra-M6VeFTz33x9Y4eRx0EQqTpIaaO5RDvuiJnHLsf0jwtvLjggydl0PG9mCzz3Lj-jtC9W58ZQDGSQDaaOfkCT_ie241_qvjQmpCQBQusMlNndwj2UPbry1JGfO4I62kMYl_03V9cTNs43hJhWtMujK4oyoJuqo-no-qFSBIOLLijZKrYVC9Ei-EkjoF8aSLfQDJdY1bPFzX_wEoYRWIcLCVCNJziNYVVTBTt8RNDFG1BWrPWZYUlGipwtOwWxHMYwwprCKLVznNuRspo9DedghJBuk_-WcMmDukx4PwB_8aKSGxkefmldYjfYYNxnz68uD9Tbik6UPDDH5Hs8nH7nfY8N_XzpDhZ8_f8OydmdRqG4yvvLTCMd4cpvEuS9NImk62IuLNKlbaS_Jql3aHdMif-oZ0iA774uiEzUX1q_YB_6uaPpfAE6khhuVQ_zV2HeUlUNNNMWhQmM

GET {{KedaiOnline.API_HostAddress}}/api/kedaionline
Authorization: Bearer {{token}}
###

GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/1
Authorization: Bearer {{token}}

###

DELETE {{KedaiOnline.API_HostAddress}}/api/kedaionline/8

###

POST {{KedaiOnline.API_HostAddress}}/api/kedaionline
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Nama" : "Kedai 13",
    "Description" : "Kedai 13 Description",
    "Category" : "Nasi Kerabu",
    "HasDelivery" : "tidak",
    "ContactEmail" : "kedai12@test.com",
    "ContactNumber" : "0123456789",
    "City" : "Ayer Keroh",
    "Street" : "Jalan Ayer Keroh",
    "PostalCode" : "75-450"
}

###
GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/3

###
GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/10

###
PATCH {{KedaiOnline.API_HostAddress}}/api/kedaionline/8
Content-Type: application/json

{
    "Nama" : "Kedai 13",
    "Description" : "Kedai 12 Description",
    "HasDelivery" : "ya"
}

###

POST {{KedaiOnline.API_HostAddress}}/api/kedaionline/1/items
Content-Type: application/json

{
    "Name" : "Item 161",
    "Description" : "Item 161 Description",
    "Price" : 10.00
}

###

GET {{KedaiOnline.API_HostAddress}}/api/kedaionline/1/items/

###

DELETE {{KedaiOnline.API_HostAddress}}/api/kedaionline/1/items/

###

GET https://localhost:7039/api/kedaionline/1/items/27

###

POST {{KedaiOnline.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email" : "owner@test.com",
    "password" : "Password1!"
}

###

POST {{KedaiOnline.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password" : "Password1!"
}

###